### ISSUE TITLE
.read() syntax doesn't work in version 0.1.2

### ISSUE THREAD

**Issue by RJahedan** [krishauser/reem#3]
When running the
`from reem import KeyValueStore 
import numpy as np
import time
server = KeyValueStore("localhost")
server["foo"] = {"number": 100.0, "string": "REEM"}
print("Reading Root  : {}".format(server["foo"].read()))
print("Reading Subkey: {}".format(server["foo"]["number"].read()))`

it doesn't work and gives the following error for the `print("Reading Subkey: {}".format(server["foo"]["number"].read()))`

`reem/accessors.py", line 123, in read
    return server_value[_ROOT_VALUE_READ_NAME]
TypeError: 'int' object is not subscriptable`

**Comment by krishauser** [comment]
Works on my machine?
